CREATE DATABASE IF NOT EXISTS `exchange` COLLATE 'utf8mb4_general_ci';
DROP TABLE IF EXISTS `exchange`.`ex_order`;
CREATE TABLE `exchange`.`ex_order` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	`uid` BIGINT(20) UNSIGNED NULL DEFAULT NULL COMMENT '用户ID',
	`create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
	`update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`state` TINYINT(4) NULL DEFAULT '0' COMMENT '状态 0初始化 1成功 2失败 3部分成交 4全部成交 5已撤单 ',
	`error_msg` VARCHAR(255) NULL DEFAULT '' COMMENT '失败原因' COLLATE 'utf8mb4_general_ci',
	`order_code` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '订单编号' COLLATE 'utf8mb4_general_ci',
	`order_type` VARCHAR(50) NULL DEFAULT '' COMMENT '订单类型' COLLATE 'utf8mb4_general_ci',
	`symbol` VARCHAR(50) NULL DEFAULT '' COMMENT '币对' COLLATE 'utf8mb4_general_ci',
	`amount` DECIMAL(20,6) NULL DEFAULT '0.000000' COMMENT '成交额',
	`quantity` DECIMAL(20,6) NULL DEFAULT '0.000000' COMMENT '数量',
	`bid` DECIMAL(20,6) NULL DEFAULT '0.000000' COMMENT '出价',
	`buy_or_sell` TINYINT(1) NULL DEFAULT '0' COMMENT '0买 1卖',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='order'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
;
